# Site settings
title: Sterling Electrical Contractors | Seattle
email: aaron@secseattle.com
description: Sterling Electrical Contractors provides electrical and excavation work for commercial and residential.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "secseattle.github.io" # the base hostname & protocol for your site
github_username: "secseattle"

# Build settings
markdown: kramdown

# Custom Variables

path:
  plugins: "assets/plugins"
  css: "assets/css"
  js: "assets/js"
