# Site settings
title: Sterling Electrical Contractors | Seattle
company: Sterling Electrical Contractors
license: STERLEC859MS
email: info@secseattle.com
description: Sterling Electrical Contractors provides electrical and excavation work for commercial and residential.
about: At Sterling Electrical Contractors we know you have many choices to serve your electrical needs. We separate ourselves from our competitors by placing our customers first - thatâ€™s why we have so many smiling customers, rave reviews and enthusiastic referrals.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "secseattle.github.io" # the base hostname & protocol for your site
github_username: "secseattle"
linked_in: "company/sterling-electrical-contractors"
yelp_username: "biz/sterling-electrical-contractors-seattle"
phone_number: (425) 774-1903
address: 6125 200th St SW, Lynnwood, WA 98036
city: Lynnwood, WA
hours: "8am - 4pm"
total_clients:
total_projects:
quote: "This is an inspirational quote"
slider_text1: "Honesty. Value. Integrity"
slider_text2: "The secret of getting ahead is getting <strong>started</strong>"
slider_text3: "is ready to be part of your project. Let's get started"
slider_text4: "The secret of getting ahead is getting <strong>started</strong>"
slider_text5: "is ready to be part of your project. Let's get started"

# Build settings
markdown: kramdown

# Custom Variables
path:
  plugins: "assets/plugins"
  css: "assets/css"
  js: "assets/js"
  images: "assets/images"

# Custom Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  careers:
    output: true
    permalink: /career/:path/
  services:
    output: true
    permalink: /services/:path/
  offers:
    output: true
    permalink: /offers/:path/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: page
